Repository googleapis/jsdoc-region-tag, pull requests merged in 2020-09, with the labels that each got.

#32 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: api: cloudbuild, cla: yes, context: full

#33 fix: main was pointing to old location
  package.json
Labels: cla: yes

#36 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: cla: yes, context: full
