Repository googleapis/jsdoc-region-tag, pull requests merged in 2020-07, with the labels that each got.

#17 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#20 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: cla: yes, kokoro:force-run

#22 test: stub out system test
  .kokoro/browser-test.sh
  .kokoro/continuous/node12/browser-test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node12/browser-test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/presubmit/windows/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/release/common.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  package.json
Labels: cla: yes

#21 build: move gittatributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#23 chore: update comments for using magictoken
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes, context: none

#24 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
